"""Add profile_pic to user

Revision ID: 171f95721c49
Revises: 6f58102d982a
Create Date: 2025-08-04 11:14:21.308521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171f95721c49'
down_revision = '6f58102d982a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
