"""Add is_admin field

Revision ID: 2b1693b510e9
Revises: 7676f5e2f2c1
Create Date: 2025-08-15 11:11:25.623000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1693b510e9'
down_revision = '7676f5e2f2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('fuel_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
