"""Make fuel not nullable

Revision ID: 9b0740938a45
Revises: 
Create Date: 2025-07-31 10:50:16.463368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0740938a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_car')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('fuel_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('fuel_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('_alembic_tmp_car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mileage', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.Column('fuel', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
