"""Add fuel_type to Car

Revision ID: ad65ea88b1dc
Revises: e00338413a08
Create Date: 2025-07-30 10:13:49.641203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad65ea88b1dc'
down_revision = 'e00338413a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=False))
        batch_op.drop_column('fuel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('fuel_type')

    # ### end Alembic commands ###
